/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_stereotype13_jsonreader_MainActivity_HttpAsyncTask */

#ifndef _Included_com_example_stereotype13_jsonreader_MainActivity_HttpAsyncTask
#define _Included_com_example_stereotype13_jsonreader_MainActivity_HttpAsyncTask
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
